spring:
  security:
    user:
      name: admin
      password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""

tourapi:
  base-url: http://apis.data.go.kr/B551011/KorService1
  service-key: I4TjfUPviE7BtpQwJy2ND47A3%2BIFWw7lNPnaoEzq39BM0U1AFmkz%2BqID4tNqdRa6OlLTfxEX3Gubng09dF%2Ba3w%3D%3D