spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

jwt:
  secret: test-jwt-secret
  access-token-expiration-ms: 3600000
  refresh-token-expiration-ms: 604800000

oauth2:
  google:
    client-id: test-client-id
    client-secret: test-secret
    redirect-uri: http://localhost:3000/oauth/callback/google
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo