spring:
  application:
    name: planit

  data:
    redis:
      host: localhost
      port: 6379

  profiles:
    active: local
    include:
      - secret

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  ai:
    openai:
      base-url: https://api.groq.com/openai
      api-key: NEED_TO_INPUT_ON_SECRET
      chat:
        options:
          model: meta-llama/llama-4-scout-17b-16e-instruct

    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

tourapi:
  base-url: http://apis.data.go.kr/B551011/KorService1
  service-key: I4TjfUPviE7BtpQwJy2ND47A3%2BIFWw7lNPnaoEzq39BM0U1AFmkz%2BqID4tNqdRa6OlLTfxEX3Gubng09dF%2Ba3w%3D%3D

logging:
  level:
    org.springframework.boot.autoconfigure.mail: DEBUG