spring:
  application:
    name: planit

  data:
    redis:
      host: localhost
      port: 6379

  profiles:
    active: local
    include:
      - secret

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true