spring:
  security:
    user:
      name: admin
      password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""