spring:
  datasource:
    url: jdbc:mysql://prod-db-host:3306/planit_prod?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: prod_password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100
