-- User
INSERT INTO users (id, email, nickname, profile_image, gender, social_id, login_type,
                   social_type, role, status, created_at, updated_at, mailing_type, bio)
VALUES (1, 'user1@example.com', '유저1', 'https://example.com/img1.png', 'MALE', 'social-id-1',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저1입니다.'),
       (2, 'user2@example.com', '유저2', 'https://example.com/img2.png', 'FEMALE', 'social-id-2',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저2입니다.'),
       (3, 'user3@example.com', '유저3', 'https://example.com/img3.png', 'MALE', 'social-id-3',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저3입니다.'),
       (4, 'user4@example.com', '유저4', 'https://example.com/img4.png', 'FEMALE', 'social-id-4',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저4입니다.'),
       (5, 'user5@example.com', '유저5', 'https://example.com/img5.png', 'MALE', 'social-id-5',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저5입니다.'),
       (6, 'user6@example.com', '유저6', 'https://example.com/img6.png', 'FEMALE', 'social-id-6',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저6입니다.'),
       (7, 'user7@example.com', '유저7', 'https://example.com/img7.png', 'MALE', 'social-id-7',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저7입니다.'),
       (8, 'user8@example.com', '유저8', 'https://example.com/img8.png', 'FEMALE', 'social-id-8',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저8입니다.'),
       (9, 'user9@example.com', '유저9', 'https://example.com/img9.png', 'MALE', 'social-id-9',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저9입니다.'),
       (10, 'user10@example.com', '유저10', 'https://example.com/img10.png', 'FEMALE', 'social-id-10',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저10입니다.'),
       (11, 'user11@example.com', '유저11', 'https://example.com/img11.png', 'MALE', 'social-id-11',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저11입니다.'),
       (12, 'user12@example.com', '유저12', 'https://example.com/img12.png', 'FEMALE', 'social-id-12',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저12입니다.'),
       (13, 'user13@example.com', '유저13', 'https://example.com/img13.png', 'MALE', 'social-id-13',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저13입니다.'),
       (14, 'user14@example.com', '유저14', 'https://example.com/img14.png', 'FEMALE', 'social-id-14',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저14입니다.'),
       (15, 'user15@example.com', '유저15', 'https://example.com/img15.png', 'MALE', 'social-id-15',
        'SOCIAL', 'GOOGLE', 'USER', 'REGISTERED', NOW(), NOW(), true, '안녕하세요 유저15입니다.');

-- MateBoard Post
INSERT INTO mate (id, title, content, travel_region, travel_start_date, travel_end_date,
                  recruitment_status, mate_gender, recruit_count, created_at, updated_at, writer_id)
VALUES (1, '서울 맛집 탐방', '서울에서 핫플 돌기', 'SEOUL', '2025-05-01', '2025-05-03', 'OPEN', 'NO_PREFERENCE',
        3, NOW(), NOW(), 1),
       (2, '부산 바다 여행', '광안리에서 놀아요', 'BUSAN', '2025-05-04', '2025-05-07', 'CLOSED', 'FEMALE', 2,
        NOW(), NOW(), 1),
       (3, '강릉 커피 거리 산책', '카페 투어 갑시다~', 'GANGWON', '2025-06-01', '2025-06-02', 'OPEN',
        'MALE', 4, NOW(), NOW(), 1),
       (4, '제주 감귤 체험', '귤 따러 가요!', 'JEJU', '2025-05-10', '2025-05-12', 'OPEN', 'NO_PREFERENCE', 3,
        NOW(), NOW(), 2),
       (5, '속초 등산', '설악산 산행', 'GANGWON', '2025-05-20', '2025-05-21', 'CLOSED', 'FEMALE', 2,
        NOW(), NOW(), 2),
       (6, '여수 야경 투어', '낭만적인 밤 보내요', 'GYEONGNAM', '2025-05-15', '2025-05-16', 'OPEN',
        'NO_PREFERENCE',
        3, NOW(), NOW(), 2),
       (7, '경주 역사 여행', '불국사와 첨성대', 'GYEONGBUK', '2025-06-05', '2025-06-06', 'OPEN', 'MALE', 4,
        NOW(), NOW(), 3),
       (8, '대구 먹방', '찜갈비 투어', 'DAEGU', '2025-06-10', '2025-06-12', 'CLOSED', 'NO_PREFERENCE', 2,
        NOW(), NOW(), 3),
       (9, '대전 과학 체험', '엑스포공원 가자!', 'DAEJEON', '2025-06-15', '2025-06-17', 'OPEN', 'FEMALE', 3,
        NOW(), NOW(), 3),
       (10, '광주 예술 여행', '비엔날레 방문', 'GWANGJU', '2025-06-01', '2025-06-02', 'OPEN', 'NO_PREFERENCE',
        3, NOW(), NOW(), 4),
       (11, '춘천 호수 산책', '의암호에서 피크닉', 'GANGWON', '2025-06-04', '2025-06-05', 'OPEN',
        'NO_PREFERENCE', 2, NOW(), NOW(), 4),
       (12, '수원 화성 탐방', '역사 느끼기', 'GYEONGGI', '2025-06-07', '2025-06-08', 'CLOSED', 'FEMALE', 3,
        NOW(), NOW(), 4),
       (13, '서울 야경 투어', '남산 타워로 고고', 'SEOUL', '2025-07-01', '2025-07-02', 'OPEN', 'MALE', 3,
        NOW(), NOW(), 5),
       (14, '부산 해운대 물놀이', '시원한 여름!', 'BUSAN', '2025-07-05', '2025-07-07', 'OPEN', 'NO_PREFERENCE',
        2, NOW(), NOW(), 5),
       (15, '제주도 일주 여행', '렌트해서 떠나요', 'JEJU', '2025-07-10', '2025-07-15', 'CLOSED', 'FEMALE', 3,
        NOW(), NOW(), 5),
       (16, '제주도 일주 여행', '렌트해서 떠나요', 'JEJU', '2025-07-10', '2025-07-15', 'CLOSED', 'FEMALE', 3,
        NOW(), NOW(), 5),
       (17, '제주도 일주 여행', '렌트해서 떠나요', 'JEJU', '2025-07-10', '2025-07-15', 'CLOSED', 'FEMALE', 3,
        NOW(), NOW(), 5),
       (18, '제주도 일주 여행', '렌트해서 떠나요', 'JEJU', '2025-07-10', '2025-07-15', 'CLOSED', 'FEMALE', 3,
        NOW(), NOW(), 5),
       (19, '제주도 일주 여행', '렌트해서 떠나요', 'JEJU', '2025-07-10', '2025-07-15', 'CLOSED', 'FEMALE', 3,
        NOW(), NOW(), 5),
       (20, '제주도 일주 여행', '렌트해서 떠나요', 'JEJU', '2025-07-10', '2025-07-15', 'CLOSED', 'FEMALE', 3,
        NOW(), NOW(), 5),
       (21, '제주도 일주 여행', '렌트해서 떠나요', 'JEJU', '2025-07-10', '2025-07-15', 'CLOSED', 'FEMALE', 3,
        NOW(), NOW(), 5),
       (22, '제주도 일주 여행', '렌트해서 떠나요', 'JEJU', '2025-07-10', '2025-07-15', 'CLOSED', 'FEMALE', 3,
        NOW(), NOW(), 5),
       (23, '제주도 일주 여행', '렌트해서 떠나요', 'JEJU', '2025-07-10', '2025-07-15', 'CLOSED', 'FEMALE', 3,
        NOW(), NOW(), 5),
       (24, '제주도 일주 여행', '렌트해서 떠나요', 'JEJU', '2025-07-10', '2025-07-15', 'CLOSED', 'NO_PREFERENCE',
        3, NOW(), NOW(), 5),
       (25, '서울 나들이', '한강에서 치맥', 'SEOUL', '2025-08-01', '2025-08-02', 'OPEN', 'NO_PREFERENCE', 2,
        NOW(), NOW(), 15),
       (26, '광주 미술관 투어', '빛고을 예술 감상', 'GWANGJU', '2025-08-03', '2025-08-04', 'OPEN',
        'NO_PREFERENCE', 3, NOW(), NOW(), 15),
       (27, '강릉 해변 휴식', '커피 한 잔의 여유', 'GANGWON', '2025-08-05', '2025-08-06', 'CLOSED',
        'MALE', 3, NOW(), NOW(), 15);

--- mate_application ---
INSERT INTO mate_application (id, user_id, mate_id, status, created_at, updated_at)
VALUES (1, 1, 4,
        'PENDING', NOW(), NOW());

-- mate_comment
INSERT INTO mate_comment (id, mate_id, user_id, content, created_at, updated_at)
VALUES (1, 5, 2, '기존 댓글입니다.', NOW(), NOW());
